//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospedajes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hospedajes()
        {
            this.PaqueteHospedaje = new HashSet<PaqueteHospedaje>();
        }
    
        public string CodigoInterno { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string TipoHospedaje { get; set; }
        public decimal PrecioNochePersona { get; set; }
        public bool Activo { get; set; }
    
        public virtual Estados Estados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaqueteHospedaje> PaqueteHospedaje { get; set; }
    }
}
