//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaqueteHospedaje
    {
        public int CodigoPaquete { get; set; }
        public string CodigoHospedaje { get; set; }
        public int CantNoches { get; set; }
    
        public virtual Hospedajes Hospedajes { get; set; }
        public virtual Paquetes Paquetes { get; set; }
    }
}
