//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vuelos()
        {
            this.Paquetes = new HashSet<Paquetes>();
            this.Paquetes1 = new HashSet<Paquetes>();
        }
    
        public string Codigo { get; set; }
        public System.DateTime FechaHoraPartida { get; set; }
        public System.DateTime FechaHoraLlegada { get; set; }
        public decimal PrecioPasaje { get; set; }
        public bool Activo { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual Estados Estados1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paquetes> Paquetes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paquetes> Paquetes1 { get; set; }
    }
}
